---
name: Terraform
# https://github.com/hashicorp/setup-terraform#usage

on:
  workflow_call:
    inputs:
      working-directory:
        description: Directory in which to run Terraform commands and operations
        type: string
        default: ./
      secrets-context:
        description: JSON string containing the secrets context
        type: string
        required: true

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Parse Secrets Context
        id: parse-secrets
        run: |
          echo "${{ inputs.secrets-context }}" > secrets.json
          export SECRETS_CONTEXT=$(cat secrets.json)

      - name: view the secrets context
        shell: bash
        run: echo "$SECRETS_CONTEXT"
         
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.7

      - name: Terraform Format
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        run: terraform init
        continue-on-error: true

      - name: Terraform Validate
        run: terraform validate
        continue-on-error: true

      - name: Terraform Plan
        run: terraform plan 
        continue-on-error: true