name: Integration

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Terraform Workflow
        uses: actions/github-script@v4
        with:
          script: |
            const workflow = await github.actions.createWorkflowDispatch({
              owner: 'Pranay34', // Replace with your repository owner
              repo: 'tf-reusable-flow', // Replace with your repository name
              workflow_file: '.github/workflows/reuse.yml',
              ref: 'main',
              inputs: {
                working-directory: ${{ matrix.working-directory }},
                secrets-context: ${{ toJson(secrets) }}
              }
            });
            console.log(`Triggered workflow: ${workflow.data.name}`);
