---
name: Terraform

# https://github.com/hashicorp/setup-terraform#usage
on:
  workflow_call:
    inputs:
      working-directory:
        description: Directory in which to run Terraform commands and operations
        type: string
        default: ./
      secrets-context:
        description: Secrets context as a JSON string
        required: false
        type: string

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: View the secrets context
        shell: bash
        run: echo "$SECRETS_CONTEXT"
        env:
          SECRETS_CONTEXT: ${{ github.event.inputs.secrets-context || toJson(secrets) }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.7

      - name: Terraform Format
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        run: terraform init
        continue-on-error: true

      - name: Terraform Validate
        run: terraform validate
        continue-on-error: true

      - name: Terraform Plan
        run: terraform plan 
        continue-on-error: true
